name: Terraform Deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0 

      - name: Terraform Format Check
        run: terraform fmt -check

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Check AWS Credentials
        run: aws sts get-caller-identity
        env:  # Set environment variables for AWS credentials
          AWS_ACCESS_KEY_ID: "AKIAWG3VVFUBDXLBYA7F"
          AWS_SECRET_ACCESS_KEY: "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"
          
      - name: Terraform Plan
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
